#Signup a user
POST http://localhost:3005/api/auth/signup
Content-Type: application/json
{
  "email": "law-tekken3@hotmail.com",
  "password": "123ray"
}

# Login user
POST http://localhost:3005/api/auth/login
Content-Type: application/json
{
  "email": "lawuysal@outlook.com",
  "password": "123ray"
}